# Generated by Django 5.0.14 on 2026-05-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_alter_answer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='references',
            field=models.TextField(blank=True, help_text='Références bibliographiques ou sources médicales utilisées.', null=True),
        ),
    ]
