# Generated by Django 5.0.14 on 2026-05-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_answer_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ai_moderation_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='ai_moderation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='ai_moderation_status',
            field=models.CharField(choices=[('SAFE', 'Safe'), ('WARNING', 'Warning'), ('DANGEROUS', 'Dangerous')], default='SAFE', max_length=20),
        ),
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
