# Generated by Django 6.0.4 on 2026-05-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='diploma_file',
            field=models.FileField(blank=True, null=True, upload_to='diplomas/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='inpe_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
