# Generated by Django 6.0.4 on 2026-05-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ANSWER', 'Réponse'), ('VOTE', 'Vote'), ('COMMENT', 'Commentaire'), ('FOLLOW', 'Follow')], max_length=20),
        ),
    ]
