# Generated by Django 5.0.14 on 2026-05-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ANSWER', 'Réponse'), ('VOTE', 'Vote'), ('COMMENT', 'Commentaire'), ('FOLLOW', 'Follow'), ('MENTION', 'Mention')], max_length=20),
        ),
    ]
