# Generated by Django 6.0.4 on 2026-05-02 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='comments.comment'),
        ),
    ]
