# Generated by Django 5.0.14 on 2026-05-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tag_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='code_reference',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='system',
            field=models.CharField(choices=[('CIM10', 'CIM-10'), ('SNOMED', 'SNOMED CT'), ('SPECIALTY', 'Spécialité médicale'), ('OTHER', 'Autre')], default='SPECIALTY', max_length=20),
        ),
    ]
