# Generated by Django 6.0.4 on 2026-04-28 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('question_type', models.CharField(choices=[('CLINICAL_CASE', 'Cas clinique'), ('THEORETICAL', 'Théorique')], default='THEORETICAL', max_length=30)),
                ('status', models.CharField(choices=[('OPEN', 'Ouverte'), ('RESOLVED', 'Résolue'), ('CLOSED', 'Fermée')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='questions', to='tags.tag')),
            ],
        ),
    ]
