# Generated by Django 5.0.14 on 2026-05-10 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_rename_body_question_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='close_reason',
            field=models.CharField(choices=[('NONE', 'Aucune'), ('DUPLICATE', 'Dupliquée'), ('OFF_TOPIC', 'Hors sujet'), ('DANGEROUS', 'Conseil médical dangereux'), ('OTHER', 'Autre')], default='NONE', max_length=30),
        ),
        migrations.AddField(
            model_name='question',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
